dataset:
  train_imgs_dir: "./ACTIA/workstation/data/images"
  train_masks_dir: "./ACTIA/workstation/data/labels"
  img_type: "jpg"
  mask_type: "png"
  num_classes: 19
  class_labels:
  class_weights: [
      1.0, # road
      1.5, # sidewalk
      1.0, # building
      2.0, # wall
      2.0, # fence
      2.0, # pole
      3.0, # traffic light
      3.0, # traffic sign
      1.0, # vegetation
      2.0, # terrain
      1.5, # sky
      3.0, # person
      3.0, # rider
      1.0, # car
      0.0, # truck
      0.0, # bus
      0.0, # train
      3.0, # motorcycle
      0.0, # bicycle
    ]

wandb:
  API_KEY: "960c7d1edaf53d6de7137290cfcbbc610b77fc67"
  silent: "true" # true or false

paths:
  cfg:
    Unet: "./ACTIA/workstation/src/config/Unet.yaml"
    SegFormer: "./ACTIA/workstation/src/config/SegFormer.yaml"
