dataset:
  class_weights:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
  divide: 1
  img_type: jpg
  mask_type: png
  num_classes: 19
  train_imgs_dir: ./actia/workstation/data/XX/images
  train_masks_dir: ./actia/workstation/data/XX/labels
paths:
  cfg:
    SegFormer: ./actia/workstation/src/config/SegFormer.yaml
    Unet: ./actia/workstation/src/config/Unet.yaml
wandb:
  API_KEY: 75fb19bcedae1a5456d20fbdf6bcbf2c9603f1b3
  silent: "true"
