resize: [256, 256] # [width,height]
in_channels: 3
last_batch: -1 # put to -1 if len(dataloader)
log_masks_every: 2
batch_metrics_every: 4
img_sampling_index: 21
teacher:
  method_coarse: "CELoss" #can be JaccardLoss or DiceLoss or FocalLoss or CELoss
  method_fine: "CELoss" #can be JaccardLoss or DiceLoss or FocalLoss or CELoss
  depth: 5
  start_filts: 32
  batch_size: 16
  epochs: 16
  lr: 0.003
  save: True
  grad_acc: 2
  save_dir: "./actia/workstation/Models/Teachers"
  log_dir: "./actia/workstation/logs/Teachers"
student:
  method1: "CELoss" #can be JaccardLoss or DiceLoss or FocalLoss or CELoss
  method2: "KL_DIV"
  depth: 4
  start_filts: 8
  batch_size: 256
  epochs: 60
  lr: 0.01 #  just perfect :\
  save: True
  grad_acc: 1
  temperature: 4 #temperature for the distillation
  alpha: 0.9 #weight of the teacher loss
  decay_alpha: True
  teacher_weight_dir: "./actia/workstation/Models/Teachers/Unet/BASELINE.safetensors" # identity is just a place holder , don't forget to modify it
  save_dir: "./actia/workstation/Models/Students"
  log_dir: "./actia/workstation/logs/Students"
