resize: [256, 256] # [width,height]
in_channels: 3
last_batch: -1 # put to -1 if len(dataloader)
log_masks_every: 4
batch_metrics_every: 4
img_sampling_index: 22
teacher:
  method_coarse: "CELoss" #can be JaccardLoss or DiceLoss or FocalLoss or CELoss
  method_fine: "CELoss" #can be JaccardLoss or DiceLoss or FocalLoss or CELoss
  depth: 5
  start_filts: 32
  batch_size: 40
  epochs: 18
  lr: 0.003
  save: True
  grad_acc: 1
  save_dir: "./actia/workstation/Models/Teachers"
  log_dir: "./actia/workstation/logs/Teachers"
student:
  method1: "CELoss" #can be JaccardLoss or DiceLoss or FocalLoss or CELoss
  method2: "KL_DIV"
  depth: 4
  start_filts: 16
  batch_size: 32
  epochs: 32
  lr: 0.003 #  just perfect :\
  save: True
  grad_acc: 2
  temperature: 5 #temperature for the distillation
  alpha: 0.7 #weight of the teacher loss
  decay_alpha: True
  teacher_weight_dir: "./actia/workstation/Models/Teachers/Unet/teacher_baseline.safetensors" # identity is just a place holder , don't forget to modify it
  save_dir: "./actia/workstation/Models/Students"
  log_dir: "./actia/workstation/logs/Students"
