training:
  depth: 2
  in_channels: 3
  start_filts: 4
  batch_size: 10
  epochs: 10
  lr: 0.001
  loss_function: "WeightedCELoss" # "TverskyCEDiceWeightedLoss" or "WeightedCELoss"
  #only using reduce on plateau for now
  factor: 0.1
  patience: 10
  save: False
  save_dir: "../models/Teachers/Unet"
  log_dir: "../../logs/Teachers/Unet"
distillation:
