resize: [64, 64] # [width,height]
in_channels: 3
last_batch: -1 # put to -1 if len(dataloader)
log_masks_every: 6
batch_metrics_every: 6
img_sampling_index: 6
teacher:
  depth: 4
  start_filts: 4
  batch_size: 4
  T_0: 5
  T_mult: 2
  eta_min: 0.0005
  epochs: 120
  lr: 0.001
  save: True
  save_dir: "./actia/workstation/Models/Teachers"
  log_dir: "./actia/workstation/logs/Teachers"
student:
  depth: 3
  start_filts: 4
  batch_size: 4
  T_0: 5
  T_mult: 2
  eta_min: 0.0005
  epochs: 120
  lr: 0.001
  save: True
  temperature: 5 #temperature for the distillation
  alpha: 0.7 #weight of the teacher loss
  teacher_weight_dir: "./actia/workstation/Models/Teachers/Unet/20240725_223210.safetensors" # identity is just a place holder , don't forget to modify it
  save_dir: "./actia/workstation/Models/Students"
  log_dir: "./actia/workstation/logs/Students"
