resize: [128, 128] # [width,height]
in_channels: 3
last_batch: -1 # put to -1 if len(dataloader)
log_masks_every: 25
batch_metrics_every: 25
img_sampling_index: 25
teacher:
  depth: 4
  start_filts: 64
  batch_size: 32
  epochs: 200
  lr: 0.003
  #only using reduce on plateau for now
  factor: 0.33333
  patience: 80
  save: True
  save_dir: "./ACTIA/workstation/Models/Teachers"
  log_dir: "./ACTIA/workstation/logs/Teachers"
student:
  depth: 3
  start_filts: 8
  batch_size: 64
  epochs: 200
  lr: 0.01
  #only using reduce on plateau for now
  factor: 0.33333
  patience: 80
  save: True
  temperature: 5 #temperature for the distillation
  alpha: 0.7 #weight of the teacher loss
  teacher_weight_dir: "./ACTIA/workstation/Models/Teachers/Unet/20240725_020251.safetensors" # identity is just a place holder , don't forget to modify it
  save_dir: "./ACTIA/workstation/Models/Students"
  log_dir: "./ACTIA/workstation/logs/Students"
