training:
  depth: 2
  in_channels: 3
  start_filts: 4
  batch_size: 10
  epochs: 15
  lr: 0.001
  #only using reduce on plateau for now
  factor: 0.1
  patience: 10
  save: False
  save_dir: "../../Models/Teachers/Unet"
  log_dir: "../../logs/Teachers/Unet"
distillation:
  depth: 2
  in_channels: 3
  start_filts: 4
  batch_size: 10
  epochs: 10
  lr: 0.01
  temperature: 3
  alpha: 0.8 #weight of the teacher loss
  #only using reduce on plateau for now
  factor: 0.1
  patience: 10
  save: False
  teacher_weight_dir: "../../Models/Teachers/Unet/depth2_in3_start4_batch10_epochs1_lr0.001.safetensors"
  save_dir: "../../Models/Students/Unet"
  log_dir: "../../logs/Students/Unet"
