paths:
  datasets: "FOR-ACTIA/FF/datasets"

dataset:
  name: "cityscapes"
  train_imgs_dir: "/media/gaston/gaston1/DEV/ACTIA/workstation/datasets/cityscapes/leftImg8bit/train"
  train_masks_dir: "/media/gaston/gaston1/DEV/ACTIA/workstation/datasets/cityscapes/gtFine/train"
  test_imgs_dir: "/media/gaston/gaston1/DEV/ACTIA/workstation/datasets/cityscapes/leftImg8bit/test"
  test_masks_dir: "/media/gaston/gaston1/DEV/ACTIA/workstation/datasets/cityscapes/gtFine/test"
  img_type: "png"
  mask_type: "png"
  num_classes: 19

resize:
  H: 8
  W: 16

log_dir:

hyperparameters:
  batch_size: 4
  lr: 0.0003
  epochs: 4
  step_size: 10
  gamma: 0.5

API_KEYS:
  wandb: "960c7d1edaf53d6de7137290cfcbbc610b77fc67"
